name: ci
on: [ push, workflow_dispatch ]
jobs:
  setup:
    runs-on: macos-latest
    env:
      MACSETUP_COMMIT: ${{ github.sha }}
    steps:
      - run: |
          export MACSETUP_COMMIT
          sh -c "$(curl -L https://raw.githubusercontent.com/WillAbides/macsetup/$MACSETUP_COMMIT/download.sh)" \
          && cd ~/repos/WillAbides/macsetup \
          && ./setup.sh
