name: ci
on: [ push, workflow_dispatch ]
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - run: |
          sh -c "$(curl -L https://raw.githubusercontent.com/WillAbides/macsetup/${{ github.sha }}/download.sh)" \
          && cd ~/repos/WillAbides/macsetup \
          && ./setup.sh
