name: ci
on: [ push, workflow_dispatch ]
jobs:
  setup:
    runs-on: macos-latest
    env:
      MACSETUP_COMMIT: ${{ github.sha }}
    steps:
      - name: download and run
        run: |
          export MACSETUP_COMMIT
          sh -c "$(curl -L https://raw.githubusercontent.com/WillAbides/macsetup/$MACSETUP_COMMIT/download.sh)" \
          && cd ~/repos/WillAbides/macsetup \
          && ./setup.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: script/lint
      - run: |
          script/fmt
          if [[ -n $(git status --porcelain) ]]; then
              echo "Code is not formatted. Please run 'script/fmt' and commit the changes."
              git --no-pager diff
              exit 1
          fi
