name: ci
on: [ push, workflow_dispatch ]
jobs:
#  setup:
#    name: setup
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: "./setup.sh"
#        env:
#          HOMEBREW_BUNDLE_BREW_SKIP: "go"
#          HOMEBREW_BUNDLE_CASK_SKIP: "docker"
  setup:
    runs-on: macos-latest
    steps:
      - run: |
          sh -c "$(curl -L https://raw.githubusercontent.com/WillAbides/macsetup/${{ github.sha }}/download.sh)" \
          && cd ~/repos/WillAbides/macsetup \
          && ./setup.sh
