name: ci
on: [ push, workflow_dispatch ]
jobs:
  brew:
    name: brew
    runs-on: macos-11
    steps:
      - run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
